fishtown-analytics/docs.getdbt.com

website/docs/learn/load_data.sql

Just wanted to keep this somewhere, I feel like this isn't the worst spot ¯\_(ツ)_/¯ 
Especially since one day we may want to integrate these steps into the tutorial.

Add SQL that was used to setup tutorial

---

README.md
website/docs/learn/2a-create-a-project-dbt-cloud.md
website/docs/learn/2b-create-a-project-dbt-cli.md
website/docs/learn/3-build-your-first-models.md
website/docs/tutorial/2a-create-a-project-dbt-cloud.md
website/docs/tutorial/3-build-your-first-models.md
website/docs/tutorial/5-deploy-your-project.md

Fix relative links

---

website/docs/learn/4-test-and-document-your-project.md
website/docs/tutorial/4-test-and-document-your-project.md

Yikes! A helpful community member pointed out that this was wrong.

Fix yaml spacing (yikes)

---

website/docusaurus.config.js
website/package-lock.json
website/package.json
website/src/pages/index.js
website/src/theme/SearchBar/index.js
website/src/theme/SearchBar/styles.css
website/static/css/search.css

Adds algolia search to the docs site

add search

---

website/docs/docs/writing-code-in-dbt/jinja-context/fromjson.md

Fix typo in fromjson

---

website/src/pages/styles.js
website/src/theme/MDXComponents/index.js

Add tabs to global styles

---

website/docs/faqs/create-dependencies.md

Add FAQ for creating dependencies

---

website/docs/docs/writing-code-in-dbt/jinja-context/run_query.md

These were in the [old docs](https://dbt.readme.io/docs/run_query) (added when I was in MTL) but didn't make it across

Add (lost) usage examples

---

website/docs/docs/building-a-dbt-project/building-models/using-custom-database.md
website/docs/docs/writing-code-in-dbt/jinja-context/profiles-yml-context.md
website/sidebars.js

I missed these files in the original 0.16.0 release PR :/

0.16.0 docs update - followup

---

website/docs/docs/dbt-cloud/dbt-cloud-changelog.md
website/sidebars.js

Migrate over changelog from https://dbt.readme.io/changelog/dbt-cloud
View @ /docs/dbt-cloud/cloud-changelog

add dbt cloud changelog

---

website/docs/docs/dbt-cloud/dbt-cloud-changelog.md

my editor has a markdown autoformatter that made some changes to the formatting (these should not impact the appearance at all, just fixing markdown syntax issues.)
I ran this locally and it looked fine to me.

add dbt cloud v1.0.5 changelog

---

website/docs/docs/guides/building-packages.md
website/docs/docs/guides/migration-guide/upgrading-to-014.md
website/docs/docs/running-a-dbt-project/command-line-interface/rpc.md

Remove readme syntax

---

website/docs/docs/building-a-dbt-project/using-operations.md

Removed trailing double quotation mark

---

website/docs/docs/dbt-cloud/dbt-cloud-changelog.md

adds changelog for dbt cloud v1.0.6

dbt cloud v1.0.6 changelog

---

website/docs/faqs/example-projects.md

Creating this in anticipation of linking to it on the home page

Add example projects FAQ

---

website/docs/faqs/getting-help.md

Write this down in a public place

Add Getting Help FAQ

---

website/docs/docs/building-a-dbt-project/dont-nest-your-curlies.md

This was rendering incorrectly before

Fix poetry

---

website/docs/docs/writing-code-in-dbt/jinja-context/builtins.md

I'd added the exact macro that I use for snowflake and some background about why someone might want to use it. I've also corrected the code given in the existing macro (there was a typo).
I said I'd help document this feature when I contributed it and never did. Sorry Drew!

Update builtins.md with more detail

---

website/docusaurus.config.js
website/src/components/link/index.js
website/src/css/custom.css
website/src/pages/styles.js
website/src/theme/CodeBlock/index.js
website/src/theme/CodeBlock/inline-link.js
website/src/theme/CodeBlock/styles.module.css

Add support for markdown links in markdown code blocks
- Verify that we're not accidentally breaking existing markdown code blocks

links in markdown

---

website/docs/docs/writing-code-in-dbt/getting-started-with-jinja.md

I wanted to checkout the Jinja related sections on the website. This caught my while I was browsing the page. I think there should be an ending quote for Quoting in Jinja + YAML section's example.

getting-started-with-jinja minor page edits

---

website/src/theme/CodeBlock/inline-link.js

This PR fixes markdown links in code blocks. I had assumed that the YAML tokenizer from prism.js (the code highlighter used by docusaurus) would _always_ tokenize markdown links independently from other yaml constructs, but this is not the case.
A quick example of what went wrong before:
```yml
[some url](google.com): abc123
```
In my initial testing, I saw that prism produced the tokens:
```
[
"[someurl](google.com)",
":",
"abc123"
]
```
but after further testing, I found cases where tokens for a similar line of code were returned like:
```yml
[
"[some url](google.com): abc123
]
```
The previous implementation would detect tokens that were exact markdown links (using a regex) and it would replace those with `<Link>` tokens. For examples like the second one shown above, this had the …

fix link highlighting in markdown files

---

website/docs/docs/building-a-dbt-project/dbt-projects/configuring-query-comments.md

Adds docs for 0.16.0:
- dict-style query comments with `append` option

Add dict-style query comment docs

---

website/docs/faqs/cloud-vs-core.md

We get this question a bit (some folks from one of our partner companies were recently asking). I'm not sure if this is the right home for it, but I wanted to at least get it written down somewhere.

Add Cloud vs Core FAQ

---

website/docs/docs/dbt-cloud/on-premises/prerequisites.md

Answers a question I got via DM in dbt Slack.

Update prerequisites.md with an explanation of supported Postgres authentication methods.

---

website/docusaurus.config.js
website/src/css/custom.css

- Less padding in sidebar links
- Fixed the `reference` link b/c i noticed it was broken

reduce padding in sidebar links

---

website/docs/faqs/cloud-vs-core.md

Fix broken link

---

website/docs/docs/building-a-dbt-project/building-models/spark-configs.md
website/docs/docs/building-a-dbt-project/projects.md
website/docs/docs/building-a-dbt-project/seeds.md
website/docs/reference/project-configs/profile.md
website/docs/reference/resource-configs/database.md
website/docs/reference/resource-configs/quote_columns.md

Friday fixes

---

website/docs/learn/2a-create-a-project-dbt-cloud.md
website/docs/learn/2b-create-a-project-dbt-cli.md
website/docs/learn/3-build-your-first-models.md
website/docs/learn/4-test-and-document-your-project.md
website/docs/tutorial/2a-create-a-project-dbt-cloud.md
website/docs/tutorial/2b-create-a-project-dbt-cli.md
website/docs/tutorial/3-build-your-first-models.md
website/docs/tutorial/4-test-and-document-your-project.md

Add file headers to tutorial

---

website/docs/docs/building-a-dbt-project/projects.md

Fix broken links

---

website/docs/docs/supported-databases/profile-bigquery.md

Update the Bigquery requirements on roles that the user needs

fix/ update profile-bigquery.md with updated roles needed

---

website/docs/docs/dbt-cloud/dbt-cloud-enterprise/enterprise-permissions.md

Updating this page to be more clear on the user license required and also let clients know that they should talk to their AM to get started.

Feature/Update enterprise-permissions

---

website/docs/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-sso-with-okta.md

@drewbanin I didn't entirely remember if we wanted to recommend putting something in the filter for the default docs but up to you. Just wanted to get this fixed

Fix/update Okta docs

---

website/docs/docs/dbt-cloud/dbt-cloud-changelog.md

Changelog for dbt Cloud 1.0.8 (and 1.0.7 was missing, too!)

dbt Cloud 1.0.8 changelog

---

website/docs/docs/contributing/building-a-new-adapter.md

Fix numbering

---

website/src/css/custom.css
website/src/pages/index.js

Make homepage more dense

---

website/docs/docs/writing-code-in-dbt/jinja-context/adapter.md

Fix broken rel paths

---

website/docs/docs/building-a-dbt-project/building-models/materializations.md
website/src/css/custom.css
website/src/pages/index.js

homepage-first-draft

---

website/docs/docs/writing-code-in-dbt/getting-started-with-jinja.md

New version of jinja, new URL
Updated link to documentation

New URL for Jinja Template Docs

---

website/docs/docs/writing-code-in-dbt/jinja-context/modules.md

This reference would have helped me locate the correct datetime retrieval for my use case.

Update modules with helpful reference.

---

website/docs/learn/1-setting-up.md

We got this feedback from our last learn, thought it might be worth calling out

Add info about workflow during Learn

---

website/docs/docs/dbt-cloud/on-premises/setup.md

This will be the temporary fix for the disconnect between Github setup. We should probably create a more synced page about Github setup so it's all on one page.

Temp_fix of Github setup

---

website/docs/docs/building-a-dbt-project/dont-nest-your-curlies.md

Make the rhyme better

---

website/docs/docs/dbt-cloud/dbt-cloud-changelog.md

changelog for dbt cloud 1.0.11

changelog for v1.0.11

---

website/docs/faqs/example-projects.md

Getting Started Tutorial link in the FAQ was broken

fix broken tutorial link

---

website/docs/docs/building-a-dbt-project/snapshots.md

This adds an example of how to use `ref` to select from a snapshot in a downstream model.

Add example of snapshot ref

---

website/docs/reference/resource-properties/identifier.md

As seen in [this Slack thread](https://getdbt.slack.com/archives/C0VLZPLAE/p1590459213011300). I changed slightly vs. what I posted there after checking the compiled quoting.

Add source example: bq sharded table

---

website/docs/docs/contributing/building-a-new-adapter.md

The docs for creating a plugin are quite out of date. I updated them to reflect the current state of 0.17.0.

Make the docs reflect what dbt actually looks like now, updated links

---

website/docs/docs/dbt-cloud/dbt-cloud-changelog.md

Adds changelog for dbt Cloud 1.0.12.

add changelog for 1.0.12

---

website/docs/docs/dbt-cloud/on-premises/architecture.md
website/docs/docs/dbt-cloud/on-premises/usage-statistics.md
website/sidebars.js

Adds information about usage.getdbt.com to on-prem docs

add usage.getdbt.com to docs

---

website/docs/docs/building-a-dbt-project/snapshots.md

I removed these, but I guess they are important!

Add back meta-fields

---

website/docs/docs/writing-code-in-dbt/jinja-context/execute.md

Update execute.md to have the correct Jinja Set

---

website/docs/reference/resource-properties/identifier.md
website/docs/reference/resource-properties/schema.md

Fix sources examples

---

website/docs/docs/dbt-cloud/dbt-cloud-changelog.md

dbt cloud 1.1.0 changelog

---

website/docs/reference/resource-properties/freshness.md

Add UTC example for freshness

---

website/docs/docs/guides/migration-guide/upgrading-to-0-17-0.md

- Fix `stirng` to `string` :bowtie:

Fix typo in upgrading-to-0-17-0.md

---

website/docs/docs/writing-code-in-dbt/jinja-context/adapter.md

These changed in 0.17.0 to take a Relation object.

Update drop_schema/create_schema docs

---

website/docs/docs/dbt-cloud/dbt-cloud-enterprise.md
website/sidebars.js

add missing sidebar for dbt cloud enterprise overview

---

website/docs/docs/running-a-dbt-project/running-dbt-in-production.md

- We often see questions in the slack about using Airflow + dbt.. here's another method!
Plus @clrcrl suggested we add a reference :-)
I've checked the markdown renders correctly in vscode. 
- Do I need to check this renders correctly on the docs site?

Share another option for using dbt with Airflow

---

website/docs/docs/supported-databases/profile-spark.md
website/docs/reference/resource-configs/spark-configs.md

* Snapshots now supported. Create list of Delta-only features
* Continue stub of core features currently unsupported on Spark (I'm sure there are more)
* Add note about schema/database behavior

Updates for spark v0.17.0

---

website/docs/reference/dbt_project.yml.md
website/docs/reference/project-configs/on-run-end.md
website/docs/reference/resource-configs/alias.md
website/docs/reference/resource-configs/bigquery-configs.md
website/docs/reference/resource-configs/database.md
website/docs/reference/resource-configs/post-hook.md
website/docs/reference/resource-configs/pre-hook.md
website/docs/reference/resource-configs/redshift-configs.md
website/docs/reference/resource-configs/schema.md
website/docs/reference/resource-configs/snowflake-configs.md
website/docs/reference/resource-configs/spark-configs.md
website/docs/reference/resource-configs/sql_header.md

One of these wasn't rendering correctly, updated the others while I was there

Remove h4s

---

website/src/css/custom.css

The ALL CAPS annoyed me (DBT, `DBT_PROJECT.YML`), but when I removed it, the title font was smaller than the body, so I had to increase that.

Change admonition headers

---

website/docs/docs/running-a-dbt-project/running-dbt-in-production.md

I have written a DbtShellTask for prefect that I would like to have highlighted as an option for using dbt in production. This was suggested by Clair on [slack](https://getdbt.slack.com/archives/C0VLNUUTZ/p1591879237109500?thread_ts=1591815328.102200&cid=C0VLNUUTZ). 
Nothing to do.

Add prefect as a deployment method

---

website/docs/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-snowflake-sso.md

This updates the `Setting Up Snowflake SSO` documentation to include the diagram that explains how Snowflake SSO works in dbt Cloud.

Feature/add in Snowflake OAuth Flow Diagram

---

website/docs/docs/running-a-dbt-project/running-dbt-in-production.md

Merged the Prefect work earlier today, just making it a little tighter.
Also decided we should be less opinionated on Airflow as a choice

Improve prefect and airflow wording

---

website/docs/reference/model-configs.md
website/docs/reference/resource-configs/enabled.md
website/docs/reference/resource-configs/persist_docs.md
website/docs/reference/seed-configs.md
website/docs/reference/snapshot-configs.md
website/docs/useful_components.md

The docs for `persist_docs` didn't cover all the resources it can be applied to.

Update persist docs

---

website/package-lock.json
website/package.json

Bump docusaurus version

---

website/docs/reference/resource-configs/database.md
website/docs/reference/resource-configs/schema.md

Helpful message

---

website/docs/docs/dbt-cloud/cloud-overview.md

Adds a general overview of dbt Cloud

---

website/docs/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-supported-dbt-versions.md

This updates the list of supported dbt cloud versions

Fix/ list of dbt versions dbt Cloud supports

---

website/docs/reference/resource-properties/overrides.md

I had a question about this, so ended up documenting it. Also switched the example to be `github_source` as it makes it clearer what the source name is versus the package name,

Update overrides docs

---

website/src/css/custom.css

hopefully this helps with navigation

Make it clear which part of the docs you're in from the nav bar

---

website/docs/docs/dbt-cloud/on-premises/prerequisites.md

Adds more complete SMTP docs to the on-premises section.

more complete smtp docs

---

website/docs/reference/project-configs/config-version.md

I don't know how to check if this works but the previous link definitely didn't :) Hope this helps

Fix link to migration guide

---

website/docs/docs/dbt-cloud/dbt-cloud-changelog.md

add changelog for dbt cloud 1.1.3

---

website/docs/dbt-cli/installation-guides/macos.md

I was visiting these instructions and noticed they referenced 0.15.1 
I can't imagine that you're planning on keeping this up to date, but I thought I'd submit an PR to help get this up-to-date
Approve?

Update reference to dbt version on Mac upgrade instructions

---

website/docs/docs/guides/debugging-errors.md
website/docs/faqs/getting-help.md
website/sidebars.js
website/src/pages/index.js

This is very overdue.
Was on my mind while answering Slack questions today — just like, how can we solve 90% of these super easily

Add article on debugging

---

website/docs/dbt-cli/configure-your-profile.md

Someone mentioned this in dbt Slack so I thought thought I'd fix
Review 😄

Fix broken link on configure your profile

---

website/docs/learn/1-setting-up.md
website/docs/learn/2a-create-a-project-dbt-cloud.md
website/docs/learn/2b-create-a-project-dbt-cli.md
website/docs/learn/3-build-your-first-models.md
website/docs/learn/4-test-and-document-your-project.md
website/docs/tutorial/1-setting-up.md
website/docs/tutorial/2a-create-a-project-dbt-cloud.md
website/docs/tutorial/2b-create-a-project-dbt-cli.md
website/docs/tutorial/3-build-your-first-models.md
website/docs/tutorial/4-test-and-document-your-project.md
website/docs/tutorial/5-deploy-your-project.md

Some of these links ended up taking people _out_ of the Learn version of the site and back to the main tutorial (and vice versa). Others were to external docs links that we moved to this repo :)

Fix tutorial and learn links

---

website/docs/reference/project-configs/name.md

Trying to be more proactive about updating docs as error messages come in

Add troubleshooting section to project name

---

website/docs/reference/resource-properties/description.md

Slowly trying to turn each question into a doc

Add example of using images

---

website/docs/reference/advanced-config-usage.md

Again, question about this in Slack, wanted to write down the answer

Add usage notes about + prefix

---

website/src/css/custom.css
website/src/pages/dbt-cloud/api.js

- Updates CSS for dbt Cloud API docs

dbt Cloud API docs updates

---

website/docs/faqs/documenting-macros.md

The current suggestion results in an error

models, not macros

---

website/docs/reference/macro-properties.md
website/docs/reference/resource-properties/argument-type.md
website/sidebars.js

This was previously undocumented because I truly didn't know how this worked! Heh.

Add docs for macro argument types

---

website/docs/docs/dbt-cloud/on-premises/faqs.md
website/sidebars.js

We get a lot of questions about different customizations that can be applied to dbt Cloud. This is an especially common one. Writing this up here so that we have something we can link to, rather than writing the same Slack snippet over and over.
I've created a new FAQs page as well. There are many more docs like this to write, and I think keeping them all in the same place is a good idea.

Add on-premises faqs, ingress instructions

---

website/docs/docs/dbt-cloud/dbt-cloud-changelog.md

Changelog for dbt Cloud v1.1.4

changelog for dbt Cloud v1.1.4

---

website/docs/docs/building-a-dbt-project/using-sources.md

Added link to "source configs" doc in "using sources" for quick reference. 
Very useful item in the reference docs section!!

Add link to using-sources.md

---

.github/CODEOWNERS

@clrcrl this is my first time editing a CODEOWNERS file. I figure I can help out with a lot of the cloud PRs (like this one https://github.com/fishtown-analytics/docs.getdbt.com/pull/304#pullrequestreview-456838693)
Lmk what you think, or if there are any other dirs you'd like me to update too

add myself as codeowner for cloud resources

---

website/docs/reference/dbt_project.yml.md

Add vars to dbt_project.yml
