_redirects
Redirect tutorial.getdbt.com to docs.getdbt.com
=> Redirect tutorial.getdbt.com to docs.getdbt.com

_redirects
Redirects `/docs`/ to `/docs/introduction`. `/docs` was the landing page for Readme.io docs
=> add redirect from /docs to /docs/introduction

website/docs/docs/writing-code-in-dbt/jinja-context/exceptions.md
Noticed this today when I went to use it for the first time. If you use `{{ exceptions.warn("hello") }}` it gets resolved to `None` which can mess with your SQL.
@drewbanin -- Would you consider this a dbt bug? I expected this to work similarly to `{{ log() }}`, but my guess is that `log` was hacked to not return `None`.
=> Update exceptions example

website/docs/docs/building-a-dbt-project/dbt-projects/configuring-query-comments.md
The current instructions suggest `query-comment: None`.
That will actually make your query comment the string "None".
Users should either leave it blank (`query-comment:`) or null (`query-comment: null`)
The existing docs are incorrect!
=> Update the query-comment docs to accurately describe how to disable query comments

_redirects
cc @clrcrl 
This PR changes the redirects in cloud to point from the old Readme URLs to the new docusaurus api docs
=> change redirects for dbt cloud api methods

website/docs/docs/running-a-dbt-project/using-the-command-line-interface/configure-your-profile.md
Tiny docs fix to close a '`' tag.
=> Fix syntax highlighting for no-partial-parse

website/docs/docs/supported-databases/profile-bigquery.md
Copying the `gcloud` oauth command didn't work as the command had a trailing quote `"`. 
Removing it allows the command to work as displayed.
¯\\_(ツ)_/¯
=> Remove trailing quote from oauth command

website/docs/docs/building-a-dbt-project/building-models/bigquery-configs.md, website/docs/docs/building-a-dbt-project/building-models/configuring-incremental-models.md, website/docs/docs/building-a-dbt-project/building-models/snowflake-configs.md, website/docs/docs/building-a-dbt-project/building-models/spark-configs.md, website/docs/docs/supported-databases.md, website/docs/docs/supported-databases/profile-presto.md, website/docs/docs/supported-databases/profile-spark.md, website/sidebars.js
- Update Presto profile (as of 0.15.3)
- Update Spark profile (as of 0.15.3)
- Add "Spark specific configurations" feature list
- Move "Configuring incremental strategy" from Snowflake/BigQuery pages (duplicated) into "Configuring incremental models," with links back to Snowflake, BigQuery, and Spark specific configs
=> Spark, Presto, incremental strategy updates

website/docs/reference/dbt_project.yml.md, website/src/theme/CodeBlock/inline-link.js
@drewbanin, leading spaces seem to be gobbled up:
```
snpashots:
[<snapshot-configs>](snapshot-configs)
```
Is getting rendered as:
```
snapshots:
<snapshot-configs>
```
=> WIP: Use hyperlinked yaml

website/docs/docs/contributing/building-a-new-adapter.md
=> fix typo: `adaper_macro`

website/sidebars.js
I wanted to make a PR to bring the seed configs into line with how we did the project configs.
Two different PRs open here:
- Option 1 (this PR): Nest all model/seed/ configs under a heading `resource configs`:
- Option 2 ([PR](https://github.com/fishtown-analytics/docs.getdbt.com/pull/102), [preview](https://deploy-preview-102--docs-getdbt-com.netlify.app/reference/resource-configs/alias)): Nest each config under a separate sub-heading.
- Option 3 (not done): break up into "general configurations" (enabled, tags, etc) and "model configurations/seed configurations/snapshot configurations". But then things like `schema` apply to some but not all resources ¯\_(ツ)_/¯
Please watch this [Loom](https://www.loom.com/share/534c492ac696404793bec3343bd59867) where I talk about the two options …
=> Option 1 sidebars

website/docs/docs/writing-code-in-dbt/jinja-context/on-run-end-context.md
I wanted to use the grant_usage_to_schemas macro in my local project. After copying and pasting the code from the docs, I noticed there were a couple things missing that I needed to change in order for the macro to work. These changes include adding `schema` in front of the schema variable in the macro. I then put single quotes around the user in the grant block in the dbt_project.yml
I built the docs locally and I see my changes on the on run end context page.
=> Fix on-run-end context docs

website/docs/docs/building-a-dbt-project/building-models/using-custom-schemas.md
On the [page describing custom schemas](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas/), an unescaped underscore character in a cell of the table is causing unintentional italics. And, it makes the Resulting schema incorrect.
This change escapes the underscore, fixing the issue. 
**Currently**
**With this PR**
=> Escape underscore character to not have unintentional italics

website/docusaurus.config.js
As requested in #44 , YAML highlighting currently does not differentiate between keys and values.
The docs site relies on Docusaurs, which [uses Prism for syntax highlighting](https://v2.docusaurus.io/docs/markdown-features/#syntax-highlighting).
I tried a few of the different [Prism themes](https://github.com/FormidableLabs/prism-react-renderer/tree/master/src/themes), but most of them also had the same colors for YAML keys and values. Also, I thought changing the theme may be too large of a change for this issue.
So, the PR still imports the same nightOwl theme that was used before, but makes a small change to account for YAML keys. I chose a color that looked decent from the [nightOwl theme](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/themes/nightOwl.js#L62) …
=> Modify Prism nightowl theme to improve YAML syntax highlighting

website/docs/docs/running-a-dbt-project/command-line-interface/rpc.md
I spent some time working to set up VSCode to support a remote compiler using RPC, before discovering that RPC support had been removed for Windows.
=> Update RPC docs to note Windows not supported

website/docs/docs/guides/migration-guide/upgrading-to-0-17-0.md, website/sidebars.js
Adds initial information about upgrading to v0.17.0 for folks looking to use the pre-release of dbt. There's more to write here for the actual release, but this will give folks enough info to use the new pre-release code.
=> 0.17.0 migration guide

website/docs/docs/building-a-dbt-project/testing-and-documentation/testing.md
I think the logic in the test is accidentally flipped.
Reviewing testing documentation I noticed the test logic didn't seem right.  The test should pass if no rows are returned, therefore, I think `where pct_null < 0.05` should be changed to `where pct_null >= 0.05`.
make sure I'm not crazy
=> Update sample test logic

website/src/css/custom.css
resolves #155
This css change prevents navbar items from collapsing. I also needed to specify the width for the logo to prevent it from shrinking horizontally when between screen breakpoints. Last, I fixed up an issue where active tabs were colored white when the navbar collapsed into the hamburger menu (screenwidth < 960px)
=> Fix for collapsing navbar links

_redirects, website/docusaurus.config.js, website/package-lock.json, website/package.json, website/src/theme/CodeBlock/README.md, website/src/theme/CodeBlock/index.js, website/src/theme/CodeBlock/styles.module.css
Upgrades to alpha 55
Changes:
- Make nav links bold when any sub-pages of that nav link are selected
- Make code blocks scroll horizontally (resolves #170)
- Adds native admonitions / callouts
FYI - you might need to delete your `node_modules` dir before running `npm i` to make this work. You should probably make a backup before deleting it :)
Let's rip out the Callout and Alert classes and replace them with [admonitions](https://v2.docusaurus.io/docs/markdown-features#calloutsadmonitions)
=> upgrade to alpha 55

website/docs/learn/2a-create-a-project-dbt-cloud.md
Updated link so it points to the correct dbt Learn page instead of the tutorial page (which uses BigQuery and has the repo creation step that was already done).
Also, in this file it says to name your Github Repo `dbt Learn - [initialsurname]`. However, the [Setting Up](https://docs.getdbt.com/learn/setting-up) page says to name it `dbt-learn-[initialsurname]`
=> Updated tutorial link to learn link

website/docs/reference/resource-configs/persist_docs.md
Updating from config-version 1 to 2 break the previous persist_docs configuration
Clarify use of `persist_docs` using `config-version: 2`
When updating to config-version 2 the current suggested configuration generate an "unused configuration paths" warning.
I just wanted to propose this clarification because I found myself confused when updating to the new config-version.
=> Clarify use of persist_docs using config-version 2

website/docs/docs/building-a-dbt-project/package-management.md
Native rendering interprets these versions as floats, which results in an error. I'm sure this copy could be a lot better.
=> Add a note about major.minor vs major.minor.patch

website/docs/reference/resource-configs/bigquery-configs.md
https://cloud.google.com/bigquery/docs/release-notes#June_09_2020 partitioning is no longer required to use clustering.
=> Remove note about partitioning requirement

website/docs/docs/building-a-dbt-project/using-sources.md, website/docs/faqs/exclude-table-from-freshness.md
Looks like the old syntax of `freshness: {}` does not work anymore and will still run the freshness test against the table that has an emptied out config. The `null` flag still works and does also look like the cleaner implementation. I opted to just drop the old syntax altogether.
=> Deprecate outdate freshness syntax

website/docs/faqs/exclude-table-from-freshness.md
Very simple typographical error with `you can use set`. Just dropped the word `use`.
=> fix very minor typo error

website/docs/docs/introduction.md
The model name is `payments` in the file description, but in the DAG and description below, the model is called `orders`. this change is for clarification
=> change model description name

website/docs/docs/guides/migration-guide/upgrading-to-0-17-0.md, website/docs/reference/dbt-jinja-functions.md, website/docs/reference/dbt-jinja-functions/as_bool.md, website/docs/reference/dbt-jinja-functions/as_native.md, website/docs/reference/dbt-jinja-functions/as_number.md, website/docs/reference/dbt-jinja-functions/as_text.md, website/sidebars.js
* Add reference docs for `is_bool`, `is_number`, `is_native`
* Update `is_text` and 0.17.0 migration guide with changelogs, callouts
* Reflects changes in https://github.com/fishtown-analytics/dbt/pull/2618
Confirm that the pseudo-code I wrote as examples _actually_ works
**Update:** All the example code is working when I've checked out https://github.com/fishtown-analytics/dbt/pull/2618. One catch: the `freshness` example for `is_native` works _without_ the `is_native` filter. I'm guessing that the coercion-to-dict is already happening because of hologram. Can you think of a better example?
=> 0.17.1: opt-in native env rendering

website/docusaurus.config.js
- Check netlify builtin env vars to determine the deployment environment
- in prod and for local dev, use https://www.getdbt.com
- in a build preview, use the netlify-generated URL
- Confirm that the branch preview works and the `og:image` meta tag uses the netlify deploy url
Netlify docs on env vars [here](https://docs.netlify.com/configure-builds/environment-variables/#build-metadata)
=> dynamically set site baseurl for netlify

website/docs/docs/building-a-dbt-project/tests.md
Change the example data test to point to the default file path for tests, which is `test`, instead of `tests`, which is the path I always put it in by accident.
I know dbt is wrong for making this one folder singular and all the rest plural, but the default directory names go way back. Maybe we should add that to the 1.0 milestone.
=> Change example data test path

.github/pull_request_template.md, RELEASE.md, _headers, netlify.toml, website/Makefile, website/docusaurus.config.js
I added Netlify config (`netlify.toml`) for branch-based deployment of the long-lived `next` branch, which will serve prerelease docs.
Here's the site: https://next--docs-getdbt-com.netlify.app/
For prettiness' sake, we'll want to CNAME this to `docs-next.getdbt.com`, but that's not _actually_ a blocker.
I defined two new environment variables:
* `ALGOLIA_INDEX_NAME`: `dbt` normally, `dbt-next` for prerelease docs
* `DISCLAIMER`: I just added the word "Prerelease " in some prominent places. We could/should add a bright warning banner to the top of the homepage / every page as well.
Also:
* Added `X-robots-tag = "noindex"` as a header for the `next` deployment
* Netlify already/automatically adds this header for all preview (PR-based) deployments
* In Netlify, I turned off all branch-based …
=> Prerelease docs site
